volumes:
  db_data:

networks:
  app_network:
    driver: bridge

#x-shared_environment: &shared_environment
#  LOG_LEVEL: debug
#  DATABASE_HOST: db
#  DATABASE_NAME: auto24_database
#  DATABASE_USERNAME: admin
#  DATABASE_PASSWORD: admin_password

services:
  nginx:
    image: nginx:1.26.2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Storage:/app/Storage
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - app_network

  app:
    image: auto24:app
    build:
      context: .
    volumes:
      - ./.env:/app/.env
      - ./Storage:/app/Storage
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - '8080:8080'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    
  migrate:
    image: auto24:migrate
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks:
      - app_network
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0

  revert:
    image: auto24:revert
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    networks:
      - app_network
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: auto24_database
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - '5432:5432'
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
